apiVersion: apps/v1
kind: Deployment
metadata:
  name: willplayground-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willplayground
  template:
    metadata:
      labels:
        app: willplayground
    spec:
      containers:
      - name: web
        image: wil42/playground:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: willplayground-service
  namespace: dev
spec:
  selector:
    app: willplayground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 80
